apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   prometheus.io/scrape: 'true'
  name: "{{ default "submission-preview" .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "submission-preview" .Values.name }}"
    service-group: "{{ .Values.labels.service_group }}"
    log-style: uwsgi
    env: "{{ .Values.namespace }}"

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "submission-preview" .Values.name }}"
