language: python
cache: pip
sudo: required
env:
  - MIN_SCORE=9 BOTO_CONFIG=/dev/null   # This is the dumbest thing. https://github.com/travis-ci/travis-ci/issues/7940
services:
  - docker
os:
  - linux
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install --dev
  - pipenv run nose2 --with-coverage --coverage-report=term-missing
after_success:
  - coveralls
  - "./tests/lint.sh preview"
  - "./tests/style.sh preview"
  - "./tests/type-check.sh preview"